### ISSUE TITLE
QML

### ISSUE THREAD

**Issue by ShalokShalom** [briskml/brisk#118]
Hi there :)

Do you plan to use QML for Linux? 

What do you criticize about it?

**Comment by naartjie** [comment]
@ShalokShalom do you know much about QML? Do you think it's a good choice for cross-platform targets?

I see there is an [OCaml library](https://github.com/Kakadu/lablqml) for it.

**Comment by ShalokShalom** [comment]
It is built for it. Nokia has bought Qt with the purpose to build the ultimate cross-platform toolkit, the documentation, the implementation, the community, all is built around it. 

Nokia has then sold it very cheap because they went bankrupt, as we all know. 
It is also the widest used open source toolkit in that perspective and has [lots](https://doc.qt.io/qtcreator/creator-using-qt-quick-designer.html) of [cool](https://github.com/mikalv/awesome-qt-qml) stuff.  

Yes, Kakadu has a nice library for it.

**Comment by wokalski** [comment]
I was wondering about licensing. We'd like to use QT or GTK only for linux (MacOS and Windows have their own libraries.) I know that both are widely in use today. Are you able to provide some more background why one is better than another?

**Comment by ShalokShalom** [comment]
Yes, MacOS and Windows have their own libraries. They do not look much better, or offer more performance. You cant tell the difference apart, you just pay multitudes of development costs. 

You can look into this talk, which shows both the benefits of Qt over GTK, as well as Qt`s performance cross platform. 

Realise that this guy is using Qt Widgets, which is not hardware accelerated and has zero capabilities to run on mobile hardware, like Qt Quick alias QML can do: https://www.youtube.com/watch?v=ON0A1dsQOV0

**Comment by wokalski** [comment]
They look, perform, and most importantly feel better than QT. I think we might have miscommunicated the purpose of Brisk somewhere but its goal is indeed providing the cross platform toolkit which communicates with system UI libraries behind the scenes.

That said, there is a place for Qt in Brisk - for Linux development.

To clarify a bit; we are striving to create a unified API for UI development on various platforms similarly to React Native. It means that on the mac we're binding to AppKit, on iOS to UIKit, on Windows to Windows 10 SDK, Android Views on Android etc.

**Comment by ShalokShalom** [comment]
You reimplimenting what is already there and that in multiple views. And you are tying to do that with a very small team, where a group of professional developers spend years over years. 

Qt6 will actually be very similar as your proposal also.

https://blog.qt.io/blog/2017/02/06/native-look-feel/

**Comment by wokalski** [comment]
Point taken @ShalokShalom. It's unclear to me what's the purpose of this issue? Please clarify what's the actionable here. If this was just a question feel free to close it. Thanks!

**Comment by ShalokShalom** [comment]
It's unclear to me what's the point of this project? 

As initially asked, I was wondering if you use QML/Qt for Linux. Which includes Android for me.

In my personal view - and this is covered by observations of individuals when looking at the different implementations - is the work that Qt has done undisguisable integration of interface elements, compared to their native implementation.

**Comment by wokalski** [comment]
The point of this project is to provide a uniform, cross platform library for developing user interfaces which use native widgets behind the scenes. Regarding Linux (but not Android), yes, I believe Qt might be the best choice there.

**Comment by ShalokShalom** [comment]
And I simply think working together with a company, that also happens to be a huge open source community, makes sense.
