### ISSUE TITLE
Error when running `esy` in ./examples/hacker-news

### ISSUE THREAD

**Issue by naartjie** [briskml/brisk#121]
I get the following error when running `esy` in `./examples/hacker-news`:

(esy version `0.5.6` and `0.5.7`)

```

error: command failed: 'dune' 'build' '@all' '-p' 'hacker-news' (exited with 127)
esy-build-package: exiting with errors above...
error: build failed with exit code: 1

esy: exiting due to errors above
```

**Comment by naartjie** [comment]
I was chatting to @wokalski about this, and it's an issue with `esy` apparently, when the path is too long.

@wokalski I tried to searching their [issues](https://github.com/esy/esy/issues) but I couldn't find it. Do you know if it's been logged there?

**Comment by joprice** [comment]
This one? https://github.com/esy/esy/issues/943

**Comment by naartjie** [comment]
@joprice that looks like the same error, yup, thank you!

**Comment by naartjie** [comment]
I tested esy/esy#985 and it fixes this issue.
