### ISSUE TITLE
Unrecognised processing directive and token

### ISSUE THREAD

**Issue by TrakBit** [briskml/brisk#23]
Unrecognised processing directive on all the header files in **Cocoa_stubs.c** 

```
#import <caml/threads.h>
^^^^^^^
```
and unrecognised token on annotations

```
@interface View : NSView
^
```
Any idea what's causing this ?

**Comment by TrakBit** [comment]
Hey @rauanmayemir,  yeah I suppose that's why the error occurs since `classes` are also a part of objective-c. so what's the roadmap for this ? 
I can try to rewrite it in C.

**Comment by rauanmayemir** [comment]
You don't have to. `clang` understands this if you just pass `-x objective-c` to the compiler.

Note that we don't use XCode when working on stubs. I couldn't figure out all the ARC warnings, but you can try playing around with it.

If you run `esy bootstrap:cocoa`, it will create an XCode project from xcodegen spec.

`esy bootstrap:mac` will create an XCode project in `BRTesterMac/mac` that you can build and run. The steps would be:

```
% from the root
esy install
esy build:mac
esy bootstrap:mac
esy run:mac
```

**Comment by TrakBit** [comment]
Those steps end up showing this
`error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

**Comment by rauanmayemir** [comment]
Do you have XCode on your mac? You'll also need to install XCode command line tools.

**Comment by TrakBit** [comment]
Yeah I have that already installed. How do I use that for running ?

**Comment by rauanmayemir** [comment]
You don't use it, you just need it for `xcodebuild` to work from command line. `esy run:mac` would be the one calling those commands.

**Comment by TrakBit** [comment]
This command `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` got the job done :-).
