### ISSUE TITLE
Project Logo

### ISSUE THREAD

**Issue by wokalski** [briskml/brisk#47]
It'd be really cool to have a project logo that can be easily identified with brisk.

**Comment by osenvosem** [comment]
Hello guys. ✋

I spent some time and came up with these options.

### Two neutral tones
![var 2](https://user-images.githubusercontent.com/6762673/51988178-1e725280-24b5-11e9-8d6c-f84f890774de.png)

### Multiple red tones with a pattern
![var 1](https://user-images.githubusercontent.com/6762673/51988190-24683380-24b5-11e9-84c2-30930149a92a.png)

### Cold, more serious
![var 3](https://user-images.githubusercontent.com/6762673/51988676-5a59e780-24b6-11e9-950f-3c2e0bc45e32.png)

Hope you like it.

**Comment by wokalski** [comment]
Hey,

WOW, thank you for that! I really like the color pattern of the first one 😄. I'm worried the letters are a bit too thin. It might look a bit skinny when the logo is small, what do you think?

**Comment by rauanmayemir** [comment]
Thank you!
I like the first one most, too.

What's the idea behind `I` stylization?

**Comment by osenvosem** [comment]
I think we can make it smaller and see what they look like. 🙂

![var 2 copy](https://user-images.githubusercontent.com/6762673/52001760-41aafb00-24d1-11e9-8bcb-e9c1b85cab1b.png)
![var 1 copy](https://user-images.githubusercontent.com/6762673/52001758-41aafb00-24d1-11e9-96d8-96b514ff99cb.png)
![var 3 copy](https://user-images.githubusercontent.com/6762673/52001762-41aafb00-24d1-11e9-82d0-d2c3a04f5635.png)

**Comment by rauanmayemir** [comment]
It looks good, but now I read 'BR/SK'.

**Comment by osenvosem** [comment]
@rauanmayemir the idea is to visualize the attitude of the word's definition, make it more dynamic using diagonal lines.

**Comment by osenvosem** [comment]
@rauanmayemir yes, it definitely visually resembles the '/' character. Will think about it.

**Comment by rauanmayemir** [comment]
I love first and second. They both look like they could be further styled into square symbol signs.

**Comment by osenvosem** [comment]
And with color:

![new var 1](https://user-images.githubusercontent.com/6762673/52005915-e8949480-24db-11e9-8325-ae65913ed1f6.png)

---

![new var 2](https://user-images.githubusercontent.com/6762673/52005916-e92d2b00-24db-11e9-92e3-2f86b76586f6.png)

**Comment by wokalski** [comment]
We've got in touch with @nic0lino to do some broader branding work for us and he also came up with some nice designs. We'll publish them when they are ready 👍.

**Comment by wokalski** [comment]
![color horizontal1](https://user-images.githubusercontent.com/1693190/52243457-f9794780-28d9-11e9-806b-162f760b0757.png)
![rounded quare color1](https://user-images.githubusercontent.com/1693190/52243463-00a05580-28da-11e9-85b6-6b5ffb774e05.png)
![square color icon1](https://user-images.githubusercontent.com/1693190/52243467-0302af80-28da-11e9-80ea-501cf92b7375.png)

FYI we settled on this branding. I think it fits our philosophy and the logo is both memorable and simple!

Thanks @nic0lino for your work on this. Thanks to @osenvosem for the initial push on this!
