### ISSUE TITLE
Minimize the amount of lifecycles

### ISSUE THREAD

**Issue by wokalski** [briskml/brisk#8]
[This is](https://github.com/briskml/brisk/blob/master/src/lib/ReactCore.rei#L74-L78) the current list of lifecycles. I'm not convinced that we need all of them and I'd like to come up with a minimal set. I know @rickyvetter and @cristianoc have some thoughts on this.

**Comment by cristianoc** [comment]
The hope is that with `getderivedStateFromProps`, one can get to a minimal set. Some experimentation needed.
